<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Engine.Plugin.Renderer.Clustered</AssemblyName>
    <RootNamespace>Engine.Plugin.Renderer.Clustered</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\engine_cs\Engine.Plugins\Engine.Plugins.csproj" />
    <ProjectReference Include="..\..\engine_cs\Engine.Renderer\Engine.Renderer.csproj" />
    <ProjectReference Include="..\..\Game\Engine.Game.csproj" />
    <ProjectReference Include="..\Renderer.DDGI\Engine.Plugin.Renderer.DDGI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="plugin.json" />
  </ItemGroup>
</Project>
